package com.sammwy.milkshake.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import com.sammwy.milkshake.Schema;

/**
 * Marks a field as the unique identifier for a document in the database.
 * This annotation indicates which field should be used as the primary key
 * when persisting and retrieving documents.
 * 
 * <p>
 * Example usage:
 * 
 * <pre>
 * {@code
 * @ID(auto = true)
 * private String id;
 * }
 * </pre>
 * 
 * @see Schema
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface ID {
    /**
     * Specifies whether the ID should be automatically generated by the database.
     * When set to true (default), the system will generate a unique identifier
     * if none is provided during object creation.
     * 
     * @return true if the ID should be auto-generated, false if it should be
     *         manually assigned
     */
    boolean auto() default true;
}